services:
  - type: web
    name: ke-holidays-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ke-holidays-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12

databases:
  - name: ke-holidays-db
    plan: free
    databaseName: holidays
    user: postgres
